### ISSUE TITLE
サンプルの再生結果

### ISSUE THREAD

**Issue by Sigureya** [effekseer/pixi-effekseer#3]
先に結論

エラーで止まる割合は結構多い。
メモリ不足はどうしようもない。
連番画像なら落ちないので、Effekseer本体からefkを出力する要領でツクール用連番アニメを出力する機能。
連番画像だけではなく、アニメーションの定義ファイルを出せばいいなと。

公式サンプルからダウンロードしたデータの内、再生できたものとそうでないものを列挙
また、mqoを含むデータのモデル表示エラーは、エラーに含まない
モデルがバグっていても、再生の開始と終了が適正であれば、正しく動いたとする

エラーの内容の説明

フリーズ
エフェクトの再生が開始されない状態
ゲームループ自体は正常に動いている

表示されない
表示はされないが、終了タイミングだけ正しく取得される

落ちる
例外が飛んで落ちる

終了しない
エフェクトは出るが、終了処理が行われない

Effekseer公式エフェクト
https://effekseer.github.io/jp/contributes/Effekseer01/index.html
どれもそこそこ正しく動く。

リーメベルタ ～願いを叶える秘宝と塔の守り人～エフェクト
https://effekseer.github.io/jp/contributes/NextSoft01/index.html

MagicFire1/再生できない
MagicHeal2/エラー落ち
MagicShield/表示されない
MagicWater/フリーズ

ピエールエフェクトvol.1
https://effekseer.github.io/jp/contributes/Pierre01/index.html

Atmosphere/フリーズ
Background/落ちる
MissileBoost/終了しない
SonicBoom/フリーズ

ピエールエフェクトvol.2
https://effekseer.github.io/jp/contributes/Pierre02/index.html
Sword_Lightningは正しく再生できるが、それ以外はフリーズ
Sword_Storm/vecotr.length_error

AndrewFMさん 投稿エフェクト
https://effekseer.github.io/jp/contributes/AndrewFM01/index.html
どれもフリーズするか、メモリ確保に失敗して落ちるか

tktkエフェクト
https://effekseer.github.io/jp/contributes/tktk01/index.html
以下のものが最後まで再生できない
hozyo1
Sword4
Sword21
Wind1

以下のものが落ちる
Arrow1
Blow1
Blow3
Blow5
Blow7
Blow10
Blow11
Blow13
Blow15
Cure2
Cure6
Cure7
Dark1
Dark2
Fire2
Fire4
Fire5
Fire6
Fire7
hozyo2
hozyo3
Light3
Magic2
Soil1
Sword15
Sword16
Sword20

vector.length_error
Fire1
Sword11

**Comment by durswd** [comment]
大分バージョンが上がってしまったためクローズします。
